### ISSUE TITLE
Nice job trying to set the font-family once!

### ISSUE THREAD

**Issue by jzhu01** [zzoom/prj-rev-bwfs-dasmoto#1]
Seen here: https://github.com/zzoom/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L1-L4

I believe your issue is that the font-families are on a different line. Once you move it to the same line, you should be able to remove all the other duplicate stylings of font-family.

**Comment by zzoom** [comment]
not sure i completely understand but, having the font-family on a different lines does make a difference!?
And it works i was able to remove all  the other font families for this exercise. 
Thank you!
