### ISSUE TITLE
Suggestion - instead of strong, use span

### ISSUE THREAD

**Issue by jzhu01** [zzoom/prj-rev-bwfs-dasmoto#3]
Seen here: https://github.com/zzoom/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L37

Since the strong tag is a stylistic one (i.e. it changes the styling fo the content inside, bolding it) I recommend using a span instead. This way, we can ensure our CSS contains all the CSS, and the HTML doesn't contain any.

**Comment by zzoom** [comment]
ok will do!
