### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [zzoom/prj-rev-bwfs-dasmoto#5]
Great job on this project! I really liked your use of a universal selector, and how clean and easy to read your code was. In terms of improvement, I recommend removing the font-weight:bold on your h2s, replacing the strong tags you have in the HTML for spans, and removing duplicate font-family stylings. 

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the awesome work! ^_^

**Comment by zzoom** [comment]
Thank you for pointing me to the extra knowledge w3schools location! 
Appreciate it!
